export const locations = [
  {
    image: "/assets/location-img-placeholder.webp",
    title: "Alpha Miami (K-10)",
    address: "8000 SW 56th St.",
    city: "Miami, Florida 33155",
    tuition: "$40000",
    buttonText: "Apply Now",
    buttonHref: "#",
    buttonClassName: "alpha-btn-warm-secondary",
  },
  {
    image: "/assets/location-img-placeholder.webp",
    title: "Alpha Austin (K-8)",
    address: "123 Main St.",
    city: "Austin, Texas 78701",
    tuition: "$35000",
    buttonText: "Apply Now",
    buttonHref: "#",
    buttonClassName: "alpha-btn-warm-secondary",
  },
  {
    image: "/assets/location-img-placeholder.webp",
    title: "Alpha Houston (K-8)",
    address: "456 Oak Ave.",
    city: "Houston, Texas 77002",
    tuition: "$37000",
    buttonText: "Apply Now",
    buttonHref: "#",
    buttonClassName: "alpha-btn-warm-secondary",
  },
  {
    image: "/assets/location-img-placeholder.webp",
    title: "Alpha Dallas (K-8)",
    address: "789 Pine Rd.",
    city: "Dallas, Texas 75201",
    tuition: "$36000",
    buttonText: "Apply Now",
    buttonHref: "#",
    buttonClassName: "alpha-btn-warm-secondary",
  },
  {
    image: "/assets/location-img-placeholder.webp",
    title: "Alpha Orlando (K-8)",
    address: "101 Orange Blvd.",
    city: "Orlando, Florida 32801",
    tuition: "$34000",
    buttonText: "Apply Now",
    buttonHref: "#",
    buttonClassName: "alpha-btn-warm-secondary",
  },
]; 